{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chatapp.fullname" . }}
  labels:
    {{- include "chatapp.labels" . | nindent 4 }}
    release: obs # Should match the name of the kube-prometheus-stack release
spec:
  selector:
    matchLabels:
      {{- include "chatapp.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: management
      path: /actuator/prometheus
      interval: 15s
{{- end }}
