
env:
  S3_PUBLIC_ENDPOINT: "https://s3-t1ichat-staging.ddnsfree.com"
  FRONTEND: "https://t1ichat-frontend-staging-732519168410.asia-southeast1.run.app"

ingress:
  managedCertificate:
    domains:
      - "t1ichat-staging.ddnsfree.com"
  hosts:
    - host: "t1ichat-staging.ddnsfree.com"
      paths:
        - path: /
          pathType: Prefix