# GKE Production Profile - App
replicaCount: 3

service:
  type: NodePort

image:
  tag: "latest"
  pullPolicy: Always

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 400m
    memory: 1Gi

ingress:
  className: "gce"
  annotations:
    kubernetes.io/ingress.allow-http: "false"
  managedCertificate:
    enabled: true
    domains:
      - "t1ichat.ddnsfree.com"
  hosts:
    - host: "t1ichat.ddnsfree.com"
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 7
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
