
ingress:
  annotations:
    kubernetes.io/ingress.allow-http: "true"
  managedCertificate:
    enabled: false
    domains:
      - "t1ichat-staging.ddnsfree.com"
  hosts:
    - host: "t1ichat-staging.ddnsfree.com"
      paths:
        - path: /
          pathType: Prefix