apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
type: Opaque
stringData:
  database-username: "root"
  postgres-password: "root"
  redis-password: "redispassword"
  kafka-user: "user"
  kafka-password: "user-password"
  client-passwords: "user-password"
  inter-broker-password: "user-password"
  controller-password: "user-password"
  jwt-secret: "vcl-vcl-vcl-vcl-vcl-vcl-vcl-vcl-vcl-vcl"
  aws-access-id: "decade"
  aws-secret-key: "decade"
  admin-user: "admin"
  admin-password: "adminpassword"