apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
type: Opaque
stringData:
  database-username: "root"
  postgres-password: "SPqe+aFq4p8VmJUCs4Ek5Q=="
  redis-password: "JXwhZALE10Hvr9YGMqdDIA=="
  client-users: "user"
  client-passwords: "5o95JqkIk8RUhO+zUJOsiw=="
  inter-broker-password: "qGWxjFgBHFDCjIRkfWi1IQ=="
  controller-password: "BCd7nw16TX5sB5dWgPanmQ=="
  jwt-secret: "PKxDj2Ebkaao6mH87dkJ6t0/WTV6FWA87RSsn1eZFzgZ8DEi/oY3LtDx4CBoivRc"
  aws-access-id: "decade"
  aws-secret-key: "7ZVx30yDNgy74sxMosARSQ=="
  admin-user: "admin"
  admin-password: "adminpassword"
