# Blueprint for Infrastructure Stack
postgresql:
  auth:
    username: root
    database: chatapp
    existingSecret: "chatapp-secrets"
    secretKeys:
      adminPasswordKey: "postgres-password"
      userPasswordKey: "postgres-password"
  primary:
    persistence:
      enabled: true

redis:
  auth:
    enabled: true
    existingSecret: "chatapp-secrets"
    existingSecretPasswordKey: "redis-password"
  master:
    persistence:
      enabled: true

kafka:
  image:
    repository: bitnamilegacy/kafka
  auth:
    clientProtocol: sasl_plaintext
    interBrokerProtocol: sasl_plaintext
    saslMechanism: plain
    existingSecret: "chatapp-secrets"
    jaas:
      clientUser: "user"
      existingSecret: "chatapp-secrets"
      existingSecretPasswordKey: "kafka-password"
  persistence:
    enabled: true
