# Blueprint for Observability Stack
kube-prometheus-stack:
  nodeExporter:
    enabled: false
  alertmanager:
    enabled: false
  grafana:
    enabled: false
  kubeProxy:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeEtcd:
    enabled: false
  coreDns:
    enabled: false
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: "" # Defined in profiles
      resources: { } # Defined in profiles

grafana:
  enabled: true
  admin:
    existingSecret: "chatapp-secrets"
    userKey: "admin-user"
    passwordKey: "admin-password"
  persistence:
    enabled: true
    size: "" # Defined in profiles
  resources: { } # Defined in profiles
  serviceMonitor:
    enabled: true
  additionalDataSources:
    - name: Prometheus
      type: prometheus
      url: http://observability-kube-prometh-prometheus:9090
      access: proxy
      isDefault: true
    - name: Loki
      type: loki
      url: http://observability-loki-gateway:80
      access: proxy
    - name: Tempo
      type: tempo
      url: http://observability-tempo:3200
      access: proxy

loki:
  deploymentMode: Monolithic
  test:
    enabled: false
  lokiCanary:
    enabled: false
  gateway:
    enabled: false
  resultsCache:
    enabled: false
  chunksCache:
    enabled: false
  monitoring:
    serviceMonitor:
      enabled: true
    selfMonitoring:
      enabled: false
      grafanaAgent:
        install: false
  loki:
    auth_enabled: false
    useTestSchema: true
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      size: "" # Defined in profiles
    resources: { } # Defined in profiles
  read:
    replicas: 0
  write:
    replicas: 0
  backend:
    replicas: 0

tempo:
  tempo:
    persistence:
      enabled: true
      size: "" # Defined in profiles
    resources: { } # Defined in profiles
    receivers:
      otlp:
        protocols:
          http:
            endpoint: "0.0.0.0:4318"
          grpc:
            endpoint: "0.0.0.0:4317"
  serviceMonitor:
    enabled: true
