POST http://localhost:8080/message/seen
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ik5hbWkiLCJwYXNzd29yZF92ZXJzaW9uIjowLCJpZCI6IjE0OGEyMGJjLTA0OWYtM2Y1NC04NTIxLTYxMjkzNGY5MTE5OCIsIm5hbWUiOiJOYW1pIiwiaWF0IjoxNzQ0Mzk2NDc4LCJleHAiOjE3NDUwMDEyNzh9.pKbl12MlWozZnK1j4UlJxqEcynxeXuLsRSLB3fxkk8c

{
  "eventType": "SEEN",
  "owner": {
    "username": "Nami",
    "name": "Nami",
    "dob": 1744470668185,
    "role": "ROLE_USER",
    "id": "148a20bc-049f-3f54-8521-612934f91198",
    "version": null,
    "avatar": {
      "uri": "https://static.vecteezy.com/system/resources/previews/009/292/244/non_2x/default-avatar-icon-of-social-media-user-vector.jpg",
      "width": 512,
      "height": 512,
      "format": "jpg"
    },
    "gender": "male"
  },
  "edges": [],
  "chatIdentifier": {
    "firstUser": "992ca204-59e9-37b2-a3f0-89f4f3f82cd5",
    "secondUser": "148a20bc-049f-3f54-8521-612934f91198"
  },
  "eventVersion": 0,
  "createdTime": 1744470668429,
  "at": 1744470668429,
  "seenEvent": {
    "at": 1744470668429
  },
  "id": "26638a6e-aeee-45bc-a882-d3d161cf9fd6",
  "partner": {
    "username": "Luffy",
    "name": "Luffy",
    "dob": 1744470668152,
    "role": "ROLE_USER",
    "id": "992ca204-59e9-37b2-a3f0-89f4f3f82cd5",
    "version": null,
    "avatar": {
      "uri": "https://static.vecteezy.com/system/resources/previews/009/292/244/non_2x/default-avatar-icon-of-social-media-user-vector.jpg",
      "width": 512,
      "height": 512,
      "format": "jpg"
    },
    "gender": "male"
  },
  "chat": {
    "identifier": {
      "firstUser": "992ca204-59e9-37b2-a3f0-89f4f3f82cd5",
      "secondUser": "148a20bc-049f-3f54-8521-612934f91198"
    },
    "owner": "148a20bc-049f-3f54-8521-612934f91198",
    "partner": "992ca204-59e9-37b2-a3f0-89f4f3f82cd5"
  },
  "sender": "148a20bc-049f-3f54-8521-612934f91198"
}