# LOCAL-ONLY Overrides for Kind
replicaCount: 1


image:
  repository: teri1712/chat-app
  pullPolicy: IfNotPresent
  tag: "local"

restartPolicy: Always

env:
  APP_PROFILES: "prod"
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  REDIS_PASSWORD: "redispassword"
  KAFKA_USER: "user"
  KAFKA_PASSWORD: "user-password"
  JWT_SECRET: "vcl-vcl-vcl-vcl-vcl-vcl-vcl-vcl-vcl-vcl"
  AWS_ACCESS_KEY_ID: "decade"
  AWS_SECRET_ACCESS_KEY: "decade"
  LOKI_URL: "http://observability-loki-gateway/loki/api/v1/push"
  OTLP_ENDPOINT: "http://observability-tempo:4318/v1/traces"

# --- LOCAL INGRESS CONFIGURATION ---
serviceMonitor:
  enabled: true

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix

