# PRODUCTION Overrides for GKE
replicaCount: 3

image:
  repository: teri1712/chat-app
  pullPolicy: IfNotPresent
  tag: "1.0.0" # Always use an immutable version tag in production

restartPolicy: Always

# --- APPLICATION ENVIRONMENT (Framework Agnostic) ---
env:
  APP_PROFILES: "prod"
  DB_USERNAME:
    valueFrom:
      secretKeyRef:
        name: chatapp-secrets
        key: database-username
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: chatapp-secrets
        key: postgres-password
  REDIS_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: chatapp-secrets
        key: redis-password
  KAFKA_USER:
    valueFrom:
      secretKeyRef:
        name: chatapp-secrets
        key: kafka-user
  KAFKA_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: chatapp-secrets
        key: kafka-password
  JWT_SECRET:
    valueFrom:
      secretKeyRef:
        name: chatapp-secrets
        key: jwt-secret
  AWS_ACCESS_KEY_ID:
    valueFrom:
      secretKeyRef:
        name: chatapp-secrets
        key: aws-access-id
  AWS_SECRET_ACCESS_KEY:
    valueFrom:
      secretKeyRef:
        name: chatapp-secrets
        key: aws-secret-key
# --- SCALING & INGRESS ---
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "gce"
  hosts:
    - host: api.chatapp.com
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
