# Master Configuration for Messenger Clone
replicaCount: 1

image:
  repository: teri1712/chat-app
  pullPolicy: IfNotPresent
  tag: "latest"

restartPolicy: Always

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

serviceMonitor:
  enabled: true

# Environment variables for the application (Framework Agnostic)
env:
  APP_PROFILES: "prod"
  DB_URL: "jdbc:postgresql://infra-postgresql:5432/chatapp"
  DB_USERNAME: "root"
  REDIS_HOST: "infra-redis-master"
  KAFKA_SERVERS: "infra-kafka:9092"
  KAFKA_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
  KAFKA_USER: "user"
  AWS_S3_REGION: "ap-southeast-1"
  AWS_S3_BUCKET: "decade-bucket"
  LOKI_URL: "http://obs-loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push"
  OTLP_ENDPOINT: "http://obs-tempo.monitoring.svc.cluster.local:4318/v1/traces"

# --- PROBES (Health Checks) ---
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8081
  initialDelaySeconds: 60
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8081
  initialDelaySeconds: 60

autoscaling:
  enabled: false

httpRoute:
  enabled: false
