version: '2.40.3'

services:
  server:
    image: teri1712/chat-app
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      ACTUATOR_USER_NAME: admin
      ACTUATOR_USER_PASSWORD: admin
      ACTUATOR_USER_ROLES: OPS
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chatapp
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
      SPRING_DATA_ELASTICSEARCH_URIS: http://elasticsearch:9200
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

    networks:
      - backend
    ports:
      - "8080:8080"
      - "8081:8081"
    #    depends_on:
    #      postgres:
    #        condition: service_healthy
    #      redis:
    #        condition: service_healthy
    #      #      kafka:
    #      #        condition: service_healthy
    #      elasticsearch:
    #        condition: service_healthy
    volumes:
      - ./logs:/app/logs


networks:
  backend:
    external: true