spring:
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  application:
    name: chat-app
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/chatapp
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 15
      connection-timeout: 30000
      minimum-idle: 5
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: jpa
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: true
        highlight_sql: true
        order_updates: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
      client-type: lettuce
      # username: username
      # password: password
      # ssl:
      #   enabled: true
      #   bundle: general
    elasticsearch:
      repositories:
        enabled: true
  mvc:
    problemdetails:
      enabled: true
  flyway:
    clean-disabled: false
    enabled: true
  elasticsearch:
    uris: http://localhost:9200

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 4
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: decade
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.add.type.headers: false
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true


actuator:
  user:
    name: admin
    password: admin
    roles: OPS
server:
  port: 8080
  error:
    include-message: always
  servlet:
    session:
      cookie:
        same-site: Lax
  # ssl:
  #   bundle: general

frontend:
  host:
    address: http://localhost:4200

jwt:
  secret: vcl-vcl-vcl-vcl-vcl-vcl-vcl-vcl-vcl-vcl

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,env,bean,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: ALWAYS

aws:
  s3:
    region: ap-southeast-1
    bucket: decade-bucket
    access:
      id: decade
      secret: decade


broker:
  topics:
    queue: queue
    room: room


websocket:
  topics:
    user: /user
    queue: /queue
    room: /room


