CREATE TABLE chat
(
    interact_time TIMESTAMP WITH TIME ZONE,
    message_count INTEGER NOT NULL,
    version       INTEGER,
    first_user    UUID    NOT NULL,
    second_user   UUID    NOT NULL,
    resource_id   INTEGER NOT NULL,
    room_name     VARCHAR(255),
    theme_id      INTEGER,
    CONSTRAINT pk_chat PRIMARY KEY (first_user, second_user)
);

CREATE TABLE chat_event
(
    id             UUID                     NOT NULL,
    sender_id      UUID,
    event_type     VARCHAR(255),
    owner_id       UUID,
    idempotent_key UUID                     NOT NULL UNIQUE,
    event_version  INTEGER                  NOT NULL,
    created_time   TIMESTAMP WITH TIME ZONE NOT NULL,
    first_user     UUID,
    second_user    UUID,
    at             TIMESTAMP,
    content        TEXT,
    media_url      VARCHAR(255),
    size           INTEGER,
    resource_id    INTEGER,
    filename       VARCHAR(255),
    uri            TEXT,
    width          INTEGER,
    height         INTEGER,
    format         VARCHAR(255),
    room_name      VARCHAR(255),
    theme_id       INTEGER,
    CONSTRAINT pk_chatevent PRIMARY KEY (id)
);

CREATE TABLE chat_order
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id         UUID,
    current_event_id UUID,
    current_version  INTEGER                                 NOT NULL,
    chat_first_user  UUID,
    chat_second_user UUID,
    CONSTRAINT pk_chatorder PRIMARY KEY (id)
);

CREATE TABLE sync_context
(
    owner_id      UUID    NOT NULL,
    event_version INTEGER NOT NULL,
    CONSTRAINT pk_synccontext PRIMARY KEY (owner_id)
);

CREATE TABLE theme
(
    id       INTEGER NOT NULL,
    uri      TEXT,
    filename TEXT,
    width    INTEGER,
    height   INTEGER,
    format   VARCHAR(255),
    CONSTRAINT pk_theme PRIMARY KEY (id)
);


CREATE TABLE user_member
(
    id       UUID         NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name     VARCHAR(255),
    dob      TIMESTAMP WITH TIME ZONE,
    role     VARCHAR(255),
    version  INTEGER,
    gender   real,
    uri      TEXT,
    filename TEXT,
    width    INTEGER,
    height   INTEGER,
    format   VARCHAR(255),
    CONSTRAINT pk_usermember PRIMARY KEY (id)
);


ALTER TABLE chat_event
    ADD CONSTRAINT FK_CHATEVENT_ON_FIUSSEUS FOREIGN KEY (first_user, second_user) REFERENCES chat (first_user, second_user);

ALTER TABLE chat_event
    ADD CONSTRAINT FK_CHATEVENT_ON_OWNER FOREIGN KEY (owner_id) REFERENCES user_member (id);

ALTER TABLE chat_event
    ADD CONSTRAINT FK_CHATEVENT_ON_SENDER FOREIGN KEY (sender_id) REFERENCES user_member (id);

ALTER TABLE chat_event
    ADD CONSTRAINT FK_CHATEVENT_ON_THEME FOREIGN KEY (theme_id) REFERENCES theme (id);

ALTER TABLE chat_order
    ADD CONSTRAINT FK_CHATORDER_ON_CHFICHSE FOREIGN KEY (chat_first_user, chat_second_user) REFERENCES chat (first_user, second_user);

ALTER TABLE chat_order
    ADD CONSTRAINT FK_CHATORDER_ON_CURRENTEVENT FOREIGN KEY (current_event_id) REFERENCES chat_event (id);

ALTER TABLE chat_order
    ADD CONSTRAINT FK_CHATORDER_ON_OWNER FOREIGN KEY (owner_id) REFERENCES user_member (id);

ALTER TABLE chat
    ADD CONSTRAINT FK_CHAT_ON_FIRST_USER FOREIGN KEY (first_user) REFERENCES user_member (id);

ALTER TABLE chat
    ADD CONSTRAINT FK_CHAT_ON_SECOND_USER FOREIGN KEY (second_user) REFERENCES user_member (id);

ALTER TABLE chat
    ADD CONSTRAINT FK_CHAT_ON_THEME FOREIGN KEY (theme_id) REFERENCES theme (id);

ALTER TABLE sync_context
    ADD CONSTRAINT FK_SYNCCONTEXT_ON_OWNER FOREIGN KEY (owner_id) REFERENCES user_member (id);
