name: CD - Production

on:
    push:
        branches: [ master ]

permissions:
    contents: read
    id-token: write


jobs:
    deploy:
        uses: ./.github/workflows/cd.yml
        with:
            GKE_CLUSTER: ${{ vars.GKE_CLUSTER }}
            FRONTEND: ${{ vars.PROD_FRONTEND }}
        secrets: inherit
