name: CD - Staging

on:
    push:
        branches: [ develop ]

permissions:
    contents: read
    id-token: write

jobs:
    deploy:
        uses: ./.github/workflows/cd.yml
        with:
            GKE_CLUSTER: ${{ vars.GKE_STAGING_CLUSTER }}
            FRONTEND: ${{ vars.STAGING_FRONTEND }}
        secrets: inherit
